# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SimCardsPowerManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('installed', models.CharField(blank=True, max_length=30)),
                ('balance', models.IntegerField(blank=True)),
                ('tariff', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('valid_date', models.DateField()),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SimCardsPowerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('installed', models.CharField(blank=True, max_length=30)),
                ('balance', models.IntegerField(blank=True)),
                ('tariff', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('valid_date', models.DateField()),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
