# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('tariff', models.CharField(max_length=30)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('cell_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim_page.MobileOperator')),
            ],
        ),
        migrations.CreateModel(
            name='SIMOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='SimCardsPowerManage',
        ),
        migrations.DeleteModel(
            name='SimCardsPowerMaster',
        ),
        migrations.AddField(
            model_name='simcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim_page.SIMOwner'),
        ),
    ]
