# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_page', '0002_auto_20160912_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='balance_renewal_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
