# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_page', '0003_simcard_balance_renewal_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='appointment',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='comment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
