# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_page', '0004_auto_20160920_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcard',
            name='login',
        ),
    ]
